import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#3f4a36",
        "surface-container-high": "#292934",
        "secondary": "#ffaaf4",
        "on-error-container": "#ffdad6",
        "primary-container": "#73e122",
        "on-primary-container": "#2a5f00",
        "secondary-container": "#f923f9",
        "inverse-primary": "#306b00",
        "on-secondary-fixed-variant": "#810082",
        "on-secondary-container": "#500050",
        "surface-container-highest": "#34343f",
        "inverse-on-surface": "#302f3a",
        "tertiary-container": "#cac7ce",
        "primary-fixed": "#8dfd41",
        "on-tertiary-container": "#545359",
        "on-background": "#e3e1ef",
        "on-tertiary-fixed": "#1b1b20",
        "on-surface-variant": "#becbb1",
        "tertiary": "#e6e3ea",
        "on-tertiary-fixed-variant": "#47464c",
        "surface-container": "#1f1f29",
        "on-primary-fixed-variant": "#235100",
        "inverse-surface": "#e3e1ef",
        "on-tertiary": "#303035",
        "on-primary-fixed": "#0a2100",
        background: "#12121c",
        primary: "#8eff42",
        "error-container": "#93000a",
        "tertiary-fixed": "#e4e1e9",
        "surface-container-lowest": "#0d0d17",
        "on-surface": "#e3e1ef",
        "secondary-fixed-dim": "#ffaaf4",
        "on-error": "#690005",
        error: "#ffb4ab",
        "surface-dim": "#12121c",
        outline: "#89957d",
        "primary-fixed-dim": "#72df20",
        surface: "#12121c",
        "surface-tint": "#72df20",
        "on-secondary-fixed": "#380038",
        "on-primary": "#163800",
        "tertiary-fixed-dim": "#c8c5cd",
        "surface-container-low": "#1b1b25",
        "surface-variant": "#34343f",
        "secondary-fixed": "#ffd7f6",
        "on-secondary": "#5b005c",
        "surface-bright": "#383843",
        "brand-teal": "#00c9a7",
        "brand-violet": "#7b2fff",
        "brand-cobalt": "#1a6fff",
        "brand-ice": "#e8f4ff",
        "brand-lavender": "#b8a9ff",
        "brand-periwinkle": "#9d8fff",
        foreground: "var(--foreground)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        md: "1.5rem",
        xl: "4rem",
        margin: "2rem",
        xs: "0.5rem",
        unit: "4px",
        gutter: "1.5rem",
        sm: "1rem",
        lg: "2.5rem",
      },
      fontFamily: {
        "body-lg": ["var(--font-manrope)"],
        "headline-xl": ["var(--font-space-grotesk)"],
        "body-md": ["var(--font-manrope)"],
        "label-md": ["var(--font-space-grotesk)"],
        "headline-md": ["var(--font-space-grotesk)"],
        "headline-lg": ["var(--font-space-grotesk)"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-xl": [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": [
          "14px",
          { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
};
export default config;
